import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const apiKey = Deno.env.get("HEYGEN_API_KEY");
    if (!apiKey) {
      return new Response(JSON.stringify({ error: "Missing HEYGEN_API_KEY" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { avatar_group_id, audio_url, title } = await req.json();

    // For full integration we need a public audio_url (or HeyGen audio_asset_id)
    if (!audio_url) {
      return new Response(
        JSON.stringify({
          error: "audio_url is required. Upload audio to a public URL or HeyGen asset, then call this function.",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Minimal connectivity check against HeyGen API
    const health = await fetch("https://api.heygen.com/v1/avatars", {
      headers: { Authorization: `Bearer ${apiKey}` },
    });

    if (!health.ok) {
      const t = await health.text();
      return new Response(
        JSON.stringify({ error: "HeyGen connectivity failed", details: t }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Example request body for Create Avatar Video V2 using audio source
    // NOTE: To actually generate, we must know a specific avatar_id in the group, and provide audio_url
    const createBody = {
      title: title || "Generated by Lovable",
      video_inputs: [
        {
          avatar: { type: "avatar", avatar_id: avatar_group_id },
          voice: { type: "audio", audio_url },
          script: { type: "audio" },
          background: { type: "color", value: "#000000" },
        },
      ],
      dimension: { width: 1280, height: 720 },
    } as const;

    const resp = await fetch("https://api.heygen.com/v2/video/generate", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(createBody),
    });

    const data = await resp.json();

    if (!resp.ok) {
      return new Response(
        JSON.stringify({ error: "HeyGen generation failed", details: data }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(JSON.stringify(data), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("heygen-generate fatal", error);
    return new Response(JSON.stringify({ error: error.message || "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});