// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibpociegfflajvhevlla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlicG9jaWVnZmZsYWp2aGV2bGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjYzNTEsImV4cCI6MjA3MjgwMjM1MX0.BSieS_dcQ9Ls8e45dmnnyAAfmQEShIaWy-G23y4ciGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});